unbind r 
bind r source-file ~/.tmux.conf

# Change the leader key from the default Ctrl + b
set -g prefix C-s 

set -g mouse on

# Change horizontal split
bind - split-window -h -c "#{pane_current_path}"

# Change vertical split 
bind . split-window -v -c "#{pane_current_path}"

# Change kill window
bind º kill-window

set-option -g status-position top 

# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @catppuccin_window_status_style "rounded"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.0'

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_cpu}"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default
